title: "Gov 50 Final Project"
author: "Kay Rollins"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
    
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(infer)
```

```{r}

sentences <-read_csv("DeathPenaltyDatabase/Death-Sentences-in-the-United-States-Since-1972-as-of-January-1-2021.csv")

executions<-read_csv("DeathPenaltyDatabase/DPIC Execution Database - U.S. Executions_2005-2022.csv")
```

```{r}
##Reading in crime data
full2021<- read_csv("ucr/2021ucr.csv")
full2020<- read_csv("ucr/2020ucr.csv")
full2019<- read_csv("ucr/2019ucr.csv")
full2018<- read_csv("ucr/2018ucr.csv")
full2017<- read_csv("ucr/2017ucr.csv")
full2016<- read_csv("ucr/2016ucr1.csv")
full2015<- read_csv("ucr/2015ucr.csv")
full2014<- read_csv("ucr/2014ucr.csv")
full2013<- read_csv("ucr/2013ucr.csv")
full2012<- read_csv("ucr/2012UCR.csv")
full2011<- read_csv("ucr/2011ucr.csv")
full2010<- read_csv("ucr/2010ucr.csv")
```

##refining the crime data so it is only the variables I want 

```{r}

full2010<-full2010|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2010) |>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == "Pennsylvania" | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Colorado" | State == "Washington" | State == "New Hampshire" | State == "Illinois" | State == "Maryland" | State == "Delaware" | State ==  "Connecticut" , 1, 0)) 
full2011<-full2011|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2011) |>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == "Pennsylvania" | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Colorado" | State == "Washington" | State == "New Hampshire"| State == "Maryland" | State == 'Delaware' | State ==  "Connecticut" , 1, 0))
full2012<-full2012|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2012) |>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' |State == "Pennsylvania" | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Colorado" | State == "Washington" | State == "New Hampshire" | State == "Maryland" | State == 'Delaware' , 1, 0))
full2013<-full2013|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2013) |>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == "Pennsylvania" | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Colorado" | State == "Washington" | State == "New Hampshire"| State == 'Delaware' , 1, 0))
full2014<-full2014|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2014) |>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Colorado" | State == "Pennsylvania" | State == "Washington" | State == "New Hampshire"| State == 'Delaware' , 1, 0))
full2015<-full2015|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2015) |>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Colorado" | State == "Washington" | State == "New Hampshire"| State == "Pennsylvania" |State == 'Delaware' , 1, 0))
full2016<-full2016|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2016) |>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Colorado" | State == "Washington" | State == "New Hampshire" | State == "Maryland" | State == "Pennsylvania" |State == 'Delaware' , 1, 0))
full2017<-full2017|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2017)|>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Colorado" | State == "Washington" | State == "New Hampshire" | State == "Maryland" | State == "Pennsylvania" , 1, 0))
full2018<-full2018|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2018)|>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Colorado" | State == "Washington" | State == "Maryland" | State == "Pennsylvania" , 1, 0))
full2019<-full2019|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2019)|>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Colorado" | State == "Maryland" | State == "Pennsylvania" , 1, 0))
full2020<-full2020|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2020) |>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Virginia" | State == "Maryland" | State == "Pennsylvania" , 1, 0))
full2021<-full2021|>
select(State, County, Violent_crime, MNNM)|>
  mutate(Year=2021) |>
  mutate(DP = if_else(State=="Alabama"|State == "Arkansas"| State == "California"| State == "Florida" | State == "Georgia" | State == 'Idaho'| State == 'Indiana' | State == 'Kansas' | State == 'Kentucky' | State =='Louisiana' | State == 'Mississippi' | State == 'Missouri' | State ==  'Montana' | State ==  'Nebraska' | State ==  'Nevada' | State == 'North Carolina' | State == 'Oklahoma' | State ==  'Ohio' | State ==  'Oregon' | State == 'South Carolina' | State ==  'South Dakota' | State ==  'Tennessee' | State ==  'Texas' | State == 'Utah' | State ==  'Wyoming' | State == "Maryland" | State == "Pennsylvania" , 1, 0))

```

```{r}
##Combining crime data from each year into a big file 
fullcrime<- rbind(full2010,full2011,full2012,full2013,full2014,full2015,full2016,full2017,full2018,full2019,full2021,full2020)


```

```{r}
#DP Sentences County by County 
sentences_count <- sentences |> 
  group_by(Jurisdiction,`Sub Jurisdiction`,Year) |>
  summarize(sent=n()) 

names(sentences_count)[names(sentences_count) == "Jurisdiction"] <- "State"
names(sentences_count)[names(sentences_count) == "Sub Jurisdiction"] <- "County"

sentences_count 
sentences_count_wide<- sentences_count|> 
  pivot_wider(names_from = Year, values_from = sent) |>
  select(State, County, `2005`, `2006`, `2007`, `2008`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`) 

```

```{r}
##Make na into 0s
sentences_count_wide<-sentences_count_wide |>
  mutate(`2005` = coalesce(`2005`, 0),
         `2006` = coalesce(`2006`, 0), 
         `2007` = coalesce(`2007`, 0),
         `2008` = coalesce(`2008`, 0),
         `2009` = coalesce(`2009`, 0),
         `2010` = coalesce(`2010`, 0),
         `2011` = coalesce(`2011`, 0),
         `2012` = coalesce(`2012`, 0),
         `2013` = coalesce(`2013`, 0),
         `2014` = coalesce(`2014`, 0),
         `2015` = coalesce(`2015`, 0),
         `2016` = coalesce(`2016`, 0),
         `2017` = coalesce(`2017`, 0),
         `2018` = coalesce(`2018`, 0),
         `2019` = coalesce(`2019`, 0),
         `2020` = coalesce(`2020`, 0))
```


```{r}
##make 5 year counts
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(a = sum(c(`2005`, `2006`, `2007`, `2008`, `2009`))) |>
  mutate(years2010 = if_else(a>0, 1, 0))
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(b = sum(c(`2006`, `2007`, `2008`, `2009`, `2010`))) |>
  mutate(years2011 = if_else(b>0, 1, 0))
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(c = sum(c(`2007`, `2008`, `2009`, `2010`, `2011`))) |>
  mutate(years2012 = if_else(c>0, 1, 0))
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(d = sum(c(`2008`, `2009`, `2010`, `2011`, `2012`))) |>
  mutate(years2013 = if_else(d>0, 1, 0))
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(e = sum(c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`))) |>
  mutate(years2014 = if_else(e>0, 1, 0))
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(f = sum(c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`))) |>
  mutate(years2015 = if_else(f>0, 1, 0))
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(g = sum(c(`2011`, `2012`, `2013`, `2014`, `2015`, `2016`))) |>
  mutate(years2016 = if_else(g>0, 1, 0))
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(h = sum(c(`2012`, `2013`, `2014`, `2015`, `2016`, `2017`))) |>
  mutate(years2017 = if_else(h>0, 1, 0))
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(i = sum(c(`2013`, `2014`, `2015`, `2016`, `2017`, `2018`))) |>
  mutate(years2018 = if_else(i>0, 1, 0))
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(j = sum(c( `2014`, `2015`, `2016`, `2017`, `2018`, `2019`))) |>
  mutate(years2019 = if_else(j>0, 1, 0))
sentences_count_wide<-sentences_count_wide |>
  rowwise() |>
  mutate(k = sum(c( `2015`, `2016`, `2017`, `2018`, `2019`, `2020`))) |>
  mutate(years2020 = if_else(k>0, 1, 0))
```



```{r}
##Execution date to execution year
executions$year<- format(as.Date(executions$Date, format="%m/%d/%Y"), "%Y")

##How many execution in each county per year 
executions_counties<- executions |> 
  group_by(`State*`,County,year) |>
  summarize(exs=n())

##Rename
names(executions_counties)[names(executions_counties) == "State*"] <- "State"
names(executions_counties)[names(executions_counties)== "year"]<- "Year"


#Pivot so I can see data better 
executions_wide<-executions_counties|>
  pivot_wider(names_from = Year, values_from = exs ) |>
   select(`State`, County, `2005`, `2006`, `2007`, `2008`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`) 

```

```{r}
##make na into 0
executions_wide<- executions_wide|>
  mutate(`2005` = coalesce(`2005`, 0),
         `2006` = coalesce(`2006`, 0), 
         `2007` = coalesce(`2007`, 0),
         `2008` = coalesce(`2008`, 0),
         `2009` = coalesce(`2009`, 0),
         `2010` = coalesce(`2010`, 0),
         `2011` = coalesce(`2011`, 0),
         `2012` = coalesce(`2012`, 0),
         `2013` = coalesce(`2013`, 0),
         `2014` = coalesce(`2014`, 0),
         `2015` = coalesce(`2015`, 0),
         `2016` = coalesce(`2016`, 0),
         `2017` = coalesce(`2017`, 0),
         `2018` = coalesce(`2018`, 0),
         `2019` = coalesce(`2019`, 0),
         `2020` = coalesce(`2020`, 0),
         `2021` = coalesce(`2021`, 0),
         `2022` = coalesce(`2022`, 0))
```

```{r}
##Make five year counts 
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(a = sum(c(`2005`, `2006`, `2007`, `2008`, `2009`))) |>
  mutate(eyears2010 = if_else(a>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(b = sum(c(`2006`, `2007`, `2008`, `2009`, `2010`))) |>
  mutate(eyears2011 = if_else(b>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(c = sum(c(`2007`, `2008`, `2009`, `2010`, `2011`))) |>
  mutate(eyears2012 = if_else(c>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(d = sum(c(`2008`, `2009`, `2010`, `2011`, `2012`))) |>
  mutate(eyears2013 = if_else(d>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(e = sum(c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`))) |>
  mutate(eyears2014 = if_else(e>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(f = sum(c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`))) |>
  mutate(eyears2015 = if_else(f>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(g = sum(c(`2011`, `2012`, `2013`, `2014`, `2015`, `2016`))) |>
  mutate(eyears2016 = if_else(g>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(h = sum(c(`2012`, `2013`, `2014`, `2015`, `2016`, `2017`))) |>
  mutate(eyears2017 = if_else(h>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(i = sum(c(`2013`, `2014`, `2015`, `2016`, `2017`, `2018`))) |>
  mutate(eyears2018 = if_else(i>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(j = sum(c( `2014`, `2015`, `2016`, `2017`, `2018`, `2019`))) |>
  mutate(eyears2019 = if_else(j>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(k = sum(c( `2015`, `2016`, `2017`, `2018`, `2019`, `2020`))) |>
  mutate(eyears2020 = if_else(k>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(l = sum(c( `2016`, `2017`, `2018`, `2019`, `2020`, `2021`))) |>
  mutate(eyears2021 = if_else(l>0, 1, 0))
executions_wide<-executions_wide |>
  rowwise() |>
  mutate(m = sum(c( `2017`, `2018`, `2019`, `2020`, `2021`, `2022`))) |>
  mutate(eyears2022 = if_else(m>0, 1, 0))

```

```{r}

executions_counties$Year <- as.double(as.character(executions_counties$Year))

alldata<- fullcrime|>
  left_join(sentences_count, by = c("County", "State","Year")) |>
  left_join(executions_counties, by = c("County", "State", "Year"))
alldata<- alldata |>
mutate(sent = coalesce(sent, 0),
         exs = coalesce(exs, 0))
```


```{r}
##First analysis! Does the elimination of a death penalty in a state lead to on average lower homicide rates-- Case of Maryland, which eliminated the DP in 2017

alldata |>
  filter (State == "Maryland")
  group_by(DP) |>
  summarize(Mean_Homicide = mean(MNNM, na.rm = TRUE))

##This table shows us that maryland's homicide count was higher before eliminating the death penalty than after eliminating it. While this is not causal, this is certainly in line with other findings about the effectivness of the death penalty. 

## Also I feel the need to clarify that I have spent a lot of time on this project I am aware this is not a very detailed analysis but I promise you I have worked a lot (my code for the rest of this should illustrate that) and it has taken me many, many hours. I know these chekpoints are supposed to make sure we are actually doing work so I promise you I am doing work. I realized while doing this analysis that I didn't have the population data for each county yet so I would need to find a different dataset, load it in, and then merge it with my existing one to fully test my hypothesis and it is already almost 5pm and I have been working on this since noon. I will go back and add more work and do that later this week, but for now I am taking a break.

```


